language: perl

perl:
   - "5.21"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"
   - "5.8"

install:
   - cpanm Perl::Critic::More Devel::EnforceEncapsulation
   - sudo apt-get install -qq aspell

script:
   - export HARNESS_OPTIONS='j:c'
   - perl Build.PL
   - ./Build authortest
